# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  life_config = debug

else ifeq ($(config),release)
  life_config = release

else ifeq ($(config),mingw)
  life_config = mingw

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := life

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

life:
ifneq (,$(life_config))
	@echo "==== Building life ($(life_config)) ===="
	@${MAKE} --no-print-directory -C . -f life.make config=$(life_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f life.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  mingw"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   life"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"